name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'

      - name: Display .NET info (for debugging)
        run: dotnet --info

      - name: Restore dependencies for API
        run: dotnet restore ./MagicVilla_VillaAPI/MagicVilla_VillaAPI.csproj

      - name: Restore dependencies for MVC
        run: dotnet restore ./MagicVilla_Web/MagicVilla_Web.csproj

      - name: List contents of MagicVilla.NUnit
        run: dir ./MagicVilla.NUnit

      - name: Restore dependencies for NUnit
        run: dotnet restore ./MagicVilla.NUnit/MagicVilla.NUnit.csproj

      - name: Build API project
        run: dotnet build ./MagicVilla_VillaAPI/MagicVilla_VillaAPI.csproj --configuration Release

      - name: Build MVC project
        run: dotnet build ./MagicVilla_Web/MagicVilla_Web.csproj --configuration Release

      - name: Run NUnit tests with detailed logging
        run: dotnet test ./MagicVilla.NUnit/MagicVilla.NUnit.csproj --configuration Release --logger "console;verbosity=detailed"

      - name: Deploy if tests pass
        if: success()
        run: |
          echo "Tests passed, deploying application..."
          xcopy /s /y /i .\MagicVilla_VillaAPI\bin\Release\net9.0\publish\* C:\inetpub\wwwroot\YourAPI
          xcopy /s /y /i .\MagicVilla_Web\bin\Release\net9.0\publish\* C:\inetpub\wwwroot\YourMVC
