name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Display .NET info (for debugging)
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore Dummy-Villiq.sln

      - name: Build solution
        run: dotnet build Dummy-Villiq.sln --configuration Release

      - name: Run NUnit tests with detailed logging
        run: dotnet test ./MagicVilla_NUnit/MagicVilla_NUnit.csproj --configuration Release --logger "console;verbosity=detailed"

      - name: Deploy if tests pass
        if: success()
        run: |
          echo "Tests passed, deploying application..."
          xcopy /s /y /i .\MagicVilla_VillaAPI\bin\Release\net6.0\publish\* C:\inetpub\wwwroot\YourAPI
          xcopy /s /y /i .\MagicVilla_Web\bin\Release\net6.0\publish\* C:\inetpub\wwwroot\YourMVC



